### ISSUE TITLE
Unite has been depleted

### ISSUE THREAD

**Issue by bala4901** [JCavallo/tryton-vim#1]
Hi, 

I intend to use this pluggin.  But after research, i found unite has been depleted. 
https://github.com/Shougo/unite.vim

Will you upgrade such as using ctrlP or others?

**Comment by JCavallo** [comment]
Hi @bala4901,

The plugin also supports denite, which is the new unite (though it requires vim8 / neovim).
https://github.com/Shougo/denite.nvim

I did not take the time to clean up what is "unite related", and it is still a little rough on the edge, but it mostly works
